version: '2'

services:

 wordpress:
  image: wordpress
  ports:
    - 8080:80
  environment:
    WORDPRESS_DB_PASSWORD: pass123
  
 mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: pass123